### ISSUE TITLE
Modifying page properties

### ISSUE THREAD

**Issue by ericp96** [Atyantik/pawjs#12]
Any way to set global styles on body or html?

**Comment by tirthbodawala** [comment]
Hey @ericp96 

For adding global styles you can  do the following:

1) Create `src/resources` and thus create `src/resources/css/style.css`
2) Include the resource CSS in `src/client.js` as below:

```javascript
// ... other imports
import "resources/css/style.css";

// ... other code
export default class ProjectClient {};
```
We should probably get the resources folder documented! Apologies.
