### ISSUE TITLE
Not working build

### ISSUE THREAD

**Issue by jsifalda** [Atyantik/pawjs#2]
Hello, I have been developing my new app with pawjs for several weeks so far and now the deploy time has came. However, when I tried to run build with following command: `npm run build && node dist/server.js` (on new machine with clean deps install) it fails on following error:  Error: Cannot find module "../app/components/Error/404"

Interestingly, I tried to build on another machine (old deps installed weeks ago) and it gives me another error: `TypeError: n is not a function`. But main point is, it fails on node dist/server.js command... 
what can I do? Or how can I bypass it at least temporary?
Do you need any other info from me in order to debug it more properly? 

Thank you very much advance.

**Comment by tirthbodawala** [comment]
Hi @jsifalda, I think the problem is not properly visible due to UglifyJS compression. We can show you how to debug it. and make temporarily disable the compression to see the proper error. Can you also please make sure that  `../app/components/Error/404` exists? if so can you please share your `src/config/classMap.js` contents?

Also, we can help you handle the issue on our Gitter channel.

**Comment by jsifalda** [comment]
Hello, I have managed to find a problem I think... the reason is, I use localStorage in my app... which does not seem to be available in nodejs env (running it with command: node dist/server.js)... how can I use localStorage in my app with pawjs? thanks in advance

**Comment by jsifalda** [comment]
Also, can you please share steps how to temporary disable uglification to debug it properly? Thanks!

**Comment by jsifalda** [comment]
actually, is possible to modify uglify plugin options?? one lib which I use in the app is not compatible with mangle option... :(

**Comment by tirthbodawala** [comment]
@jsifalda storage option is provided out of the box via pawjs you can find it in direct route components via `this.props.localStorage` ==> this localStorage is actually Cookie Storage.

To stop uglification for servers there is no such option in current version (we are adding that in upcoming stable version of pawjs) but you can directly go to `node_modules/pawjs/src/webpack/config/prod.server.babel.js` and comment the uglify plugin totally temporarily. 

Will provide a path soon.

**Comment by jsifalda** [comment]
When I disabled the uglification, I managed to found out that `TypeError: n is not a function` is actually `TypeError: require is not a function`... in one of the libraries I use. After long time researching, I managed to fix with this `"global.GENTLY": false` adding it into uglifyJS configuration...
