### ISSUE TITLE
Support for defining a proxy to avoid CORS

### ISSUE THREAD

**Issue by alessandrogurgel** [Atyantik/pawjs#22]
Is there any support to create proxy configurations to avoid CORS in development environment ?
How you recommend us to implement this in a project based on pawjs ?

**Comment by goldylucks** [comment]
would be great for me too!

**Comment by tirthbodawala** [comment]
We can add custom middleware via server.js as express proxy server. I can create a an example repo for it and can document it as well

**Comment by goldylucks** [comment]
that would be great for SSR, thanks!. 

Can you make a solution for SPA as well?

**Comment by fsiatama** [comment]
Please, I also need this urgently, thank you very much.

**Comment by tirthbodawala** [comment]
@fsiatama try the following steps:

## Install http-proxy-middleware
```bash
npm install --save http-proxy-middleware
```  
More Info at [https://github.com/chimurai/http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware)  

  
## Update `src/server.js` for adding proxy middleware
```javascript
import proxy from 'http-proxy-middleware';
import express from 'express';

// Create proxy instance
var apiProxy = proxy('http://localhost:8888/api/endpoint/');

// Create proxy middleware
var proxyMiddleware = express();
proxyMiddleware.use('/api', apiProxy);

// Add middleware to pawjs
export default class Server {
  constructor({ addMiddleware }) {
    addMiddleware(proxyMiddleware);
     // ... Other code
  }
  apply(serverHandler) {
     // ... Other code
  }
}
```
