### ISSUE TITLE
Sample using redux-saga

### ISSUE THREAD

**Issue by istack-robel** [Atyantik/pawjs#5]
client.js
```
function enhancer(sagamw) {
  return next => (reducer, initialState, enhancer) => {
    const thisStore = next(reducer, initialState, enhancer);
    sagamw.run(mySaga);

    return thisStore;

  };
}

export const reduxEnhancers = [enhancer(sagaMiddleware)]
export const reduxMiddlewares = [sagaMiddleware];
```

do the same on your server.js

**Comment by tirthbodawala** [comment]
This can now be handled by @pawjs/redux. Please refer to the plugin docs:
[https://github.com/Atyantik/pawjs/tree/master/packages/pawjs-redux](https://github.com/Atyantik/pawjs/tree/master/packages/pawjs-redux)
