### ISSUE TITLE
Hard Source WebPack Plugin

### ISSUE THREAD

**Issue by yash-thakur** [Atyantik/pawjs#6]
https://github.com/mzgoddard/hard-source-webpack-plugin

We will try to use this plugin to make consecutive builds faster.

**Comment by tirthbodawala** [comment]
@yash-thakur I have published a blog explaining how you can integrate the mentioned plugin to improve performance with PawJS v2

https://www.reactpwa.com/blog/2018/08/16/improve-build-performance-with-hardsource-webpack-plugin.html
