### ISSUE TITLE
Adding a loader to the webpack config

### ISSUE THREAD

**Issue by jpsear** [Atyantik/pawjs#9]
I can't seem to find any generic examples of how to extend the webpack config. I would like to add a loader to handle an .mp4 file.

**Comment by tirthbodawala** [comment]
@jpsear sure. I shall create a doc and share the link here before closing the task.

**Comment by tirthbodawala** [comment]
@jpsear well that is pretty much it, I would suggest the same code as above, I will create more hooks in future like
```
webpackHandler.hooks.fileLoaderExtension.tap("AddMp4Extension", (env, type, extensions) => {
   if(extensions.indexOf(".mp4") === -1) {
      extensions.push(".mp4");
   }
});
```
